service: gov-agenda-notifier

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  environment:
    IS_LAMBDA: true
    NODE_ENV: development

    TWILIO_AUTH_TOKEN: ${self:custom.TWILIO.AUTH_TOKEN} 
    TWILIO_ACCOUNT_SID: ${self:custom.TWILIO.ACCOUNT_SID} 
    TWILIO_PHONE_NUMBER: ${self:custom.TWILIO.PHONE_NUMBER} 

    PGHOST: ${self:custom.POSTGRESQL.HOST} 
    PGPORT: ${self:custom.POSTGRESQL.PORT}
    PGUSER: ${self:custom.POSTGRESQL.USER}
    PGPASSWORD: ${self:custom.POSTGRESQL.PASS}
    PGDATABASE: ${self:custom.POSTGRESQL.DBNAME}

custom:
  TWILIO:
    AUTH_TOKEN: ${file(./secrets.json):TWILIO_AUTH_TOKEN}
    ACCOUNT_SID: ${file(./secrets.json):TWILIO_ACCOUNT_SID}
    PHONE_NUMBER: ${file(./secrets.json):TWILIO_PHONE_NUMBER}
  POSTGRESQL:
    USER: ${file(./secrets.json):PGUSER}
    PASS: ${file(./secrets.json):PGPASSWORD}
    DBNAME: ${file(./secrets.json):PGDATABASE}
    PORT:
      Fn::GetAtt: [PostgreSqlRDSInstance, Endpoint.Port]
    HOST:
      Fn::GetAtt: [PostgreSqlRDSInstance, Endpoint.Address]
    VPC_CIDR: 10

plugins:
  - serverless-pseudo-parameters
resources:
  Resources:    
    ServerlessInternetGateway:
      Type: AWS::EC2::InternetGateway
      Properties:
        Tags: 
          - 
            Key: "Name"
            Value: "ServerlessInternetGateway"
      
    ServerlessVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: ${self:custom.POSTGRESQL.VPC_CIDR}.0.0.0/16
        EnableDnsSupport: true
        EnableDnsHostnames: true
        InstanceTenancy: default
        Tags: 
          - 
            Key: "Name"
            Value: "ServerlessVPC"

    ServerlessVPCGA:    
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        VpcId:
          Ref: ServerlessVPC
        InternetGatewayId:
          Ref: ServerlessInternetGateway

    ServerlessSubnetA:
      DependsOn: ServerlessVPC
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Ref: ServerlessVPC
        AvailabilityZone: ${self:provider.region}a
        CidrBlock: ${self:custom.POSTGRESQL.VPC_CIDR}.0.0.0/24
        Tags: 
          - 
            Key: "Name"
            Value: "ServerlessSubnetA"

    ServerlessSubnetB:
      DependsOn: ServerlessVPC
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Ref: ServerlessVPC
        AvailabilityZone: ${self:provider.region}b
        CidrBlock: ${self:custom.POSTGRESQL.VPC_CIDR}.0.1.0/24
        Tags: 
          - 
            Key: "Name"
            Value: "ServerlessSubnetB"

    ServerlessSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: "RDS Subnet Group"
        SubnetIds:
          - Ref: ServerlessSubnetA
          - Ref: ServerlessSubnetB
        Tags: 
          - 
            Key: "Name"
            Value: "ServerlessSubnetGroup"

    ServerlessSecurityGroup:
      DependsOn: ServerlessVPC
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: SecurityGroup for Serverless Functions
        VpcId:
          Ref: ServerlessVPC
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '0'
            ToPort: '65535'
            CidrIp: "0.0.0.0/0"
        Tags: 
          - 
            Key: "Name"
            Value: "ServerlessSecurityGroup"

    PostgreSqlRDSInstance: 
      DependsOn: ServerlessVPCGA
      Type: AWS::RDS::DBInstance
      Properties:
        Engine: postgres
        AllocatedStorage: 20
        PubliclyAccessible: true
        DBInstanceClass: db.t2.micro
        DBName: ${self:custom.POSTGRESQL.DBNAME}
        MasterUsername: ${self:custom.POSTGRESQL.USER}
        MasterUserPassword: ${self:custom.POSTGRESQL.PASS}
        VPCSecurityGroups:
        - !GetAtt ServerlessSecurityGroup.GroupId
        DBSubnetGroupName:
          Ref: ServerlessSubnetGroup

functions:
  graphql:
    handler: handler.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true